Formatting fixes.

diff --git a/dot/bashrc b/dot/bashrc
--- a/dot/bashrc
+++ b/dot/bashrc
@@ -7,8 +7,8 @@ fi
 
 # If not running interactively, don't do anything.
 case $- in
-    *i*) ;;
-      *) return;;
+  *i*) ;;
+    *) return;;
 esac
 
 ## Some general setup
@@ -124,79 +124,78 @@ export LS_COLORS='di=1:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=35:*.rpm=90'
 ## Section for running processes
 
 notify(){
-    $@
-    cd ~/.textbelt_server
+  $@
+  cd ~/.textbelt_server
 
-    echo ""
-    echo "Sending sms..."
-    message=$@
-    curl -X POST http://textbelt.com/text \
-         -d number=5126359155 \
-         -d "from=$(whoami)@$(hostname)" \
-         -d "message=Process '$message' completed: exit code $?"
-    echo ""
+  echo ""
+  echo "Sending sms..."
+  message=$@
+  curl -X POST http://textbelt.com/text \
+       -d number=5126359155 \
+       -d "from=$(whoami)@$(hostname)" \
+       -d "message=Process '$message' completed: exit code $?"
+  echo ""
 }
 
 
 ### This is for changing a git repo's protocol
 
 gitSwitchProtocol(){
-    if [ "$1" != "https" ]
-    then
-        REPO_URL=`git remote -v | grep -m1 '^origin' | sed -Ene 's#.*(https://[^[:space:]]*).*#\1#p'`
-        if [ -z "$REPO_URL" ]; then
-            echo "-- ERROR:  Could not identify Repo url."
-            echo "   It is possible this repo is already using SSH."
-            return -1
-        fi
-
-        USER=`echo $REPO_URL | sed -Ene's#https://github.com/([^/]*)/(.*).git#\1#p'`
-        if [ -z "$USER" ]; then
-            echo "-- ERROR:  Could not identify User."
-            return -1
-        fi
-
-        REPO=`echo $REPO_URL | sed -Ene's#https://github.com/([^/]*)/(.*).git#\2#p'`
-        if [ -z "$REPO" ]; then
-            echo "-- ERROR:  Could not identify Repo."
-            return -1
-        fi
-        NEW_URL="git@github.com:$USER/$REPO.git"
-
-    else
-        REMOTE=${1-origin}
-
-        REPO_URL=`git remote -v | grep -m1 "^$REMOTE" | sed -Ene's#.*(git@github.com:[^[:space:]]*).*#\1#p'`
-        if [ -z "$REPO_URL" ]; then
-            echo "-- ERROR:  Could not identify Repo url."
-            echo "   It is possible this repo is already using HTTPS instead of SSH."
-            return -1
-        fi
-
-        USER=`echo $REPO_URL | sed -Ene's#git@github.com:([^/]*)/(.*).git#\1#p'`
-        if [ -z "$USER" ]; then
-            echo "-- ERROR:  Could not identify User."
-            return -1
-        fi
-
-        REPO=`echo $REPO_URL | sed -Ene's#git@github.com:([^/]*)/(.*).git#\2#p'`
-        if [ -z "$REPO" ]; then
-            echo "-- ERROR:  Could not identify Repo."
-            return -1
-        fi
+  if [ "$1" != "https" ]
+  then
+    REPO_URL=`git remote -v | grep -m1 '^origin' | sed -Ene 's#.*(https://[^[:space:]]*).*#\1#p'`
+    if [ -z "$REPO_URL" ]; then
+      echo "-- ERROR:  Could not identify Repo url."
+      echo "   It is possible this repo is already using SSH."
+      return -1
     fi
 
-    echo "Changing repo url from "
-    echo "  '$REPO_URL'"
-    echo "      to "
-    echo "  '$NEW_URL'"
-    echo ""
+    USER=`echo $REPO_URL | sed -Ene's#https://github.com/([^/]*)/(.*).git#\1#p'`
+    if [ -z "$USER" ]; then
+      echo "-- ERROR:  Could not identify User."
+      return -1
+    fi
 
-    CHANGE_CMD="git remote set-url origin $NEW_URL"
-    `$CHANGE_CMD`
+    REPO=`echo $REPO_URL | sed -Ene's#https://github.com/([^/]*)/(.*).git#\2#p'`
+    if [ -z "$REPO" ]; then
+      echo "-- ERROR:  Could not identify Repo."
+      return -1
+    fi
+    NEW_URL="git@github.com:$USER/$REPO.git"
+  else
+    REMOTE=${1-origin}
 
-    echo "Success"
-    return 0
+    REPO_URL=`git remote -v | grep -m1 "^$REMOTE" | sed -Ene's#.*(git@github.com:[^[:space:]]*).*#\1#p'`
+    if [ -z "$REPO_URL" ]; then
+      echo "-- ERROR:  Could not identify Repo url."
+      echo "   It is possible this repo is already using HTTPS instead of SSH."
+      return -1
+    fi
+
+    USER=`echo $REPO_URL | sed -Ene's#git@github.com:([^/]*)/(.*).git#\1#p'`
+    if [ -z "$USER" ]; then
+      echo "-- ERROR:  Could not identify User."
+      return -1
+    fi
+
+    REPO=`echo $REPO_URL | sed -Ene's#git@github.com:([^/]*)/(.*).git#\2#p'`
+    if [ -z "$REPO" ]; then
+      echo "-- ERROR:  Could not identify Repo."
+      return -1
+    fi
+  fi
+
+  echo "Changing repo url from "
+  echo "  '$REPO_URL'"
+  echo "      to "
+  echo "  '$NEW_URL'"
+  echo ""
+
+  CHANGE_CMD="git remote set-url origin $NEW_URL"
+  `$CHANGE_CMD`
+
+  echo "Success"
+  return 0
 }
 
 alias -- git-switch-ssh="gitSwitchProtocol"
@@ -222,7 +221,7 @@ shopt -s checkwinsize
 
 # enable programmable completion features
 if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
-    . /etc/bash_completion
+  . /etc/bash_completion
 fi
 # bash aliases
 if [ -f ~/.bash_aliases ]; then
@@ -233,8 +232,8 @@ fi
 # and I don't want to commit to my public repo. Assumed to be in
 # ~/.bash_private/..
 for file in ~/.private/bash*; do
-    if [ -f "$file" ]
-    then
-        . "$file"
-    fi
+  if [ -f "$file" ]
+  then
+    . "$file"
+  fi
 done
